# Generated by Django 4.2.9 on 2025-03-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
